apiVersion: apps/v1
kind: Deployment
metadata:
  name: moo-vamp-test-v0.0.1
  namespace: production
  labels:
    app: moo-vamp-test
    version: "0.0.1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moo-vamp-test
      version: "0.0.1"
  template:
    metadata:
      labels:
        app: moo-vamp-test
        version: "0.0.1"
    spec:
      containers:
      - name: python-demo
        imagePullPolicy: Always
        image: "moolikethecow/python-demo:0.0.1"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          failureThreshold: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi