version: 2.1

orbs: 
  snyk: snyk/snyk@1.4.0
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

parameters:
  deploy:
    type: boolean
    default: true
  deploy_hold:
    type: boolean
    default: false
  deploy_aws:
    type: boolean
    default: false
  deploy_gcp:
    type: boolean
    default: false
  deploy_homelab:
    type: boolean
    default: false
  deploy_heroku:
    type: boolean
    default: false

commands:
  set-build-env:
    description: "Set environment variables needed for building"
    steps:
      - checkout
      - run:
          name: Setup Build Environment Variables
          command: |
            echo "export VERSION=$(cat VERSION)" >> $BASH_ENV
            source $BASH_ENV
  
jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - set-build-env
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: ${VERSION}
          lint-dockerfile: true
          treat-warnings-as-errors: true
      #- snyk/scan:
      #    docker-image-name: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:${VERSION}
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: ${VERSION}
      
  test:
    working_directory: ~/circleci-demo
    docker:
      - image: cimg/node:current
    resource_class: small
    parallelism: 2
    steps:
      - checkout
      - run: mkdir -p ./test-results/jest
      - run: npm install jest --save-dev
      - run: yarn add --dev jest-junit
      - run:
            name: Test application
            command: |
                TEST=$(circleci tests glob "./test/*.js" | circleci tests split --split-by=timings)
                npm test $TEST
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
  
  deploy-heroku:
    working_directory: ~/circleci-demo
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - set-build-env
      - heroku/install
      - heroku/check-authentication
      - heroku/push-docker-image:
         app-name: moo-python-demo
         process-types: web
      - heroku/release-docker-image:
         app-name: moo-python-demo
         process-types: web

  deploy-aws:
    working_directory: ~/circleci-demo
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - set-build-env
      - add_ssh_keys:
          fingerprints:
            - "b1:28:4c:f7:e8:bc:60:0a:51:d5:7b:5d:cf:29:64:01"
      - run:
          name: Deploy to AWS EC2 over SSH 
          command: |
            ssh -o StrictHostKeyChecking=no $AWS_SSH_USER@$AWS_SSH_HOST "docker container kill python-demo ; docker container rm python-demo && docker pull moolikethecow/python-demo:${VERSION} && docker run -d -p 8000:8000 --name python-demo moolikethecow/python-demo:${VERSION}"
  
  deploy-gcp:
    working_directory: ~/circleci-demo
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - set-build-env
      - checkout
      - run: sleep 20
      - run: echo "This is running in parallel with the deploy"
  
  deploy-homelab:
    working_directory: ~/circleci-demo
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - set-build-env
      - add_ssh_keys:
          fingerprints:
            - "30:4f:cd:85:dd:7b:f1:29:b6:bf:fb:71:a3:bc:6b:f7"
      - run:
          name: Deploy to Homelab over SSH 
          command: |
            ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "git -C /var/www/circleci/circlecinterview pull origin homelab-deploy"

workflows:
  build-test-deploy:
    when: << pipeline.parameters.deploy >>
    jobs:
      - build
      - test
      - hold:
          name: deploy-hold
          type: approval
          requires:
            - build 
            - test
      - deploy-aws:
          requires: 
           - build
           - test
           - deploy-hold
      - deploy-heroku:
          requires: 
           - build
           - test
           - deploy-hold
      - deploy-gcp:
          requires: 
           - build
           - test
           - deploy-hold

  build-test-deploy-hold:
    when: << pipeline.parameters.deploy_hold >>
    jobs:
      - build
      - test
      - hold:
          name: aws-hold
          type: approval
          requires:
            - build 
            - test
      - hold:
          name: gcp-hold
          type: approval
          requires: 
           - build
           - test
           - aws-hold
      - hold:
          name: heroku-hold
          type: approval
          requires: 
           - build
           - test
      - deploy-aws:
          requires: 
           - build
           - test
           - aws-hold
      - deploy-heroku:
          requires: 
           - build
           - test
           - heroku-hold
      - deploy-gcp:
          requires: 
           - build
           - test
           - gcp-hold
  
  build-test-aws:
    when: << pipeline.parameters.deploy_aws >>
    jobs:
      - build
      - test
      - hold:
          type: approval
          requires: 
           - build
           - test
      - deploy-aws:
          requires: 
           - build
           - test
           - hold
  
  build-test-heroku:
    when: << pipeline.parameters.deploy_heroku >>
    jobs:
      - build
      - test
      - hold:
          type: approval
          requires: 
           - build
           - test
      - deploy-heroku:
          requires: 
           - build
           - test
           - hold
  
  build-test-gcp:
    when: << pipeline.parameters.deploy_gcp >>
    jobs:    
      - build
      - test
      - hold:
          type: approval
          requires: 
           - build
           - test
      - deploy-gcp:
          requires: 
           - build
           - test
           - hold
  
  build-test-homelab:
    when: << pipeline.parameters.deploy_homelab >>
    jobs:
      - build
      - test
      - hold:
          type: approval
          requires: 
           - build
           - test
      - deploy-homelab:
          requires:
            - build
            - test
            - hold
          filters:
            branches:
              only: homelab-deploy

# VS Code Extension Version: 1.1.1